version: "3.9"

services:    
  cbo_db:
    container_name: cbo_db
    image: postgres:15
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: cbo_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  buscador_solr:
    container_name: buscador_solr
    build:
      context: .
      dockerfile: solr.Dockerfile
    ports:
      - "8983:8983"  

  api_flask:
    container_name: api_busca
    build:
      context: .
      dockerfile: api.Dockerfile 
    ports:
      - "5000:5000"
    depends_on:
      - cbo_db       
      - buscador_solr 
    environment:
      - DATABASE_URL=postgresql://postgres:123456@cbo_db:5432/cbo_db  
      - SOLR_URL=http://solr:8000/solr/cbo_ocupacao_core 

volumes:
  pgdata: {}
