version: '3.8'

services:
  cbo_db:
    image: postgres:15
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager] # Banco de dados só no nó manager
    networks:
      - app_network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: cbo_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  api_busca:
    image: alyssonp/api_busca_elastica:1.2
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role != manager]
    networks:
      - app_network
    ports:
      - "80:5000"
    environment:
      DATABASE_URL: postgresql://postgres:123456@host_db:5432/cbo_db
      URL_SOLR: Null

networks:
  app_network:
    driver: overlay

volumes:
  pgdata:
    driver: local