services:    
  cbo_db:
    container_name: cbo_db
    image: postgres:15
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: cbo_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  solr:
    container_name: solr
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - data_solar:/var/solr
    command:
      - solr-precreate
      - cbo

  api_busca:
    container_name: api_busca
    build:
      dockerfile: api.Dockerfile
    # image: api_busca
    # ports:
    #   - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - env=production
    depends_on:
      - cbo_db
      - solr
    
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api_busca

volumes:
  pgdata:
  data_solar: